version: '3'
services:
  user-service:
    build: ./user_service
    ports:
      - "5001:5001"
  order-service:
    build: ./order_service
    ports:
      - "5002:5002"
  payment-service:
    build: ./payment_service
    ports:
      - "5003:5003"
