name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: CloudLabs.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t CloudLabs.azurecr.io/${{ github.event.repository.name }}:latest .
        docker push CloudLabs.azurecr.io/${{ github.event.repository.name }}:latest

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v4
      with:
        namespace: default
        manifests: |
          deployment.yaml
          service.yaml
        images: |
          CloudLabs.azurecr.io/${{ github.event.repository.name }}:latest
